version: '3'

services:
  # Node.js Application
  app:
    build:
      context: ./app # Path to your Node.js app's Dockerfile
    container_name: nodejs-app
    restart: always
    ports:
      - "4000:3000" # Map container port to host port
    depends_on:
      - db # Ensure MongoDB is started before the app
   # environment:
   #   - NODE_ENV=production # Set the Node.js environment to production
    networks:
      - app-network

  # MongoDB Database
  db:
    image: mongo:4.4 # Use the official MongoDB image
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017" # Map container port to host port
    volumes:
      - mongodb-data:/data/db # Persist MongoDB data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=demo # MongoDB admin username
      - MONGO_INITDB_ROOT_PASSWORD=87654321 # MongoDB admin password
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb-data:
