services:
  # Mongodb service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin # MongoDB admin username
      - MONGO_INITDB_ROOT_PASSWORD=87654321 # MongoDB admin password
      
  # Node api service
  api:
    build: .
    ports:
      # local->container
      - 4000:3000
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongo_db:27017/demo
      DB_NAME: demo
    depends_on:
      - mongo_db

volumes:
  mongo_data: {}
