version: '3.9'

services:
  # Mongodb service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_data:/data/db

  # Node api service
  api:
    build: .
    ports:
      # local->container
      - 4000:3000
    environment:
      PORT: 3000
      MONGODB_URI: mongo://admin@87654321@mongo:27017/"
      DB_NAME: demo
    depends_on: 
      - mongo_db

volumes:
  mongo_data: {}
